---
title: "First Knit"
author: "Wilhelmus Elersich"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas. For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation.

## A short history of you.

Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.

### my answer

I was homeschooled. I graduated in 2021. English is easier than math, but math is more interesting. The inherent subjectivity of English is what makes it easy, while the logical basis of mathematics makes it much more intellectually fulfilling. I did best in the sciences (biology, chemistry, etc)

## Your computer and your and its capability?

For this class you need a computer you can use at home. So, what kind is it (windows, Apple, Linux)? On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself? You also need to have have internet access. How is your connection to the internet where you live?

### my answer

My computer at home is a cheap windows laptop from 2017. I would rate myself 4. My internet connection is decent; I have had no major issues recently, but I have serious issues in the past.

## Others and You?

What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be?

### my answer

I would like to be called will.

## Aspirations?

What do you want to achieve in life? What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer

I want to do Biological research. Naturally, the college subjects of most interest to me would be Biology and Chemistry. I am currently going for an AS in Biology, and I will go as far as I am able.

## Past adventures?

Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future? Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer

Aside from a short layover in Canada, I have only been to the Netherlands. I have not been in the military, but if I was drafted, I would choose the Navy. because the ocean is cool.

## Why are you taking Statistics?

Did you take Math 115 or Math 116 ? Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??\
What grade do you need to attain in stats to not upset your future plans, What is your plan?

### my answer

I am taking Math 116, because of what is stated in the question. I think i just need to pass this class, but, because of competition to get into good universities, I shall go far an A.